// components/ShippingQuoteModal.tsx
import { useState } from "react";
import { Modal, Form, InputGroup, Button, Spinner, Table, Alert } from "react-bootstrap";

type Props = { show: boolean; onHide: () => void };

type Quote = {
  carrier: "DHL" | "Aramex" | "UPS";
  speed: "standard" | "express";
  etaDays: number;
  chargeableKg: number;
  priceAED: number;
  breakdown: {
    baseAED: number;
    fuelAED: number;
    remoteAED: number;
    insuranceAED: number;
  };
};

const ISO: Record<string, string> = {
  "uae": "AE", "united arab emirates": "AE", "ae": "AE",
  "uk": "GB", "united kingdom": "GB", "gb": "GB",
  "usa": "US", "united states": "US", "us": "US",
};

function normCountry(s: string) {
  const k = (s || "").trim().toLowerCase();
  return ISO[k] || s;
}

export default function ShippingQuoteModal({ show, onHide }: Props) {
  const [from, setFrom] = useState("United Arab Emirates");
  const [to, setTo] = useState("United Kingdom");
  const [postcode, setPostcode] = useState("");
  const [weight, setWeight] = useState("1");
  const [unit, setUnit] = useState<"kg" | "lb">("kg");
  const [speed, setSpeed] = useState<"standard" | "express">("standard");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [quotes, setQuotes] = useState<Quote[]>([]);

  async function getQuotes() {
    setError(null);
    setQuotes([]);

    const w = Number(weight);
    if (!(w > 0)) return setError("Weight must be a positive number");

    const body = {
      from: normCountry(from),
      to: { country: normCountry(to), postcode: postcode.trim() || undefined },
      weightKg: unit === "kg" ? w : w * 0.45359237,
      speed,
      carriers: { DHL: true, Aramex: true, UPS: true },
    };

    setLoading(true);
    try {
      const res = await fetch("/api/shipping/quote", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json().catch(() => ({} as any));
      if (!res.ok || !data?.ok) throw new Error(data?.error || `HTTP ${res.status}`);

      setQuotes(Array.isArray(data.quotes) ? data.quotes : []);
    } catch (e: unknown) {
  const msg =
    e instanceof Error ? e.message :
    typeof e === "string" ? e :
    "Failed to get quotes";
  setError(msg);
    } finally {
      setLoading(false);
    }
  }

  function copyRow(q: Quote) {
    const txt =
`Estimate
From: ${from}
To: ${to}${postcode ? " " + postcode : ""}
Weight: ${weight} ${unit}
Speed: ${q.speed}
Carrier: ${q.carrier}
ETA: ${q.etaDays} days
Chargeable (kg): ${q.chargeableKg.toFixed(2)}
Base: ${q.breakdown.baseAED.toFixed(2)}  Fuel: ${q.breakdown.fuelAED.toFixed(2)}
Remote: ${q.breakdown.remoteAED.toFixed(2)}  Insurance: ${q.breakdown.insuranceAED.toFixed(2)}
Total: AED ${q.priceAED.toFixed(2)}
(Non-binding estimate. Final rate subject to review.)`;
    navigator.clipboard.writeText(txt).catch(() => {});
  }

  function emailRow(q: Quote) {
    const subject = encodeURIComponent("Shipping estimate request");
    const body = encodeURIComponent(
      `Please confirm/advise best rate for the following:\n\n` +
      `From: ${from}\n` +
      `To: ${to}${postcode ? " " + postcode : ""}\n` +
      `Weight: ${weight} ${unit}\n` +
      `Speed: ${q.speed}\n` +
      `Carrier: ${q.carrier}\n` +
      `ETA: ${q.etaDays} days\n` +
      `Total (AED): ${q.priceAED.toFixed(2)}\n\n` +
      `(Non-binding estimate generated by the calculator.)`
    );
    window.location.href = `mailto:support@example.com?subject=${subject}&body=${body}`; // <-- change email
  }

  return (
    <Modal show={show} onHide={onHide} centered size="lg">
      <Modal.Header closeButton>
        <Modal.Title>Shipping Calculator</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <div className="row g-3">
          <div className="col-md-5">
            <Form.Label>From</Form.Label>
            <Form.Control value={from} onChange={(e) => setFrom(e.target.value)} placeholder="UAE / AE" />
          </div>
          <div className="col-md-5">
            <Form.Label>To</Form.Label>
            <Form.Control value={to} onChange={(e) => setTo(e.target.value)} placeholder="UK / GB" />
          </div>
          {/* …inside <Modal.Body> after the form … */}

{error && <Alert variant="info" className="mt-3">{error}</Alert>}

{loading && (
  <div className="d-flex justify-content-center py-3">
    <Spinner animation="border" />
  </div>
)}

{!loading && quotes.length > 0 && (
  <>
    <Table hover responsive className="mt-3">
      <thead>
        <tr>
          <th>Carrier</th>
          <th>Service</th>
          <th>ETA</th>
          <th className="text-end">Chargeable (kg)</th>
          <th className="text-end">Base</th>
          <th className="text-end">Fuel</th>
          <th className="text-end">Remote</th>
          <th className="text-end">Insurance</th>
          <th className="text-end">Total (AED)</th>
        </tr>
      </thead>
      <tbody>
        {quotes.map((q, i) => (
          <tr key={i}>
            <td>{q.carrier}</td>
            <td>{q.speed}</td>
            <td>{q.etaDays} days</td>
            <td className="text-end">{q.chargeableKg.toFixed(2)}</td>
            <td className="text-end">{q.breakdown.baseAED.toFixed(2)}</td>
            <td className="text-end">{q.breakdown.fuelAED.toFixed(2)}</td>
            <td className="text-end">{q.breakdown.remoteAED.toFixed(2)}</td>
            <td className="text-end">{q.breakdown.insuranceAED.toFixed(2)}</td>
            <td className="text-end fw-bold">{q.priceAED.toFixed(2)}</td>
          </tr>
        ))}
      </tbody>
    </Table>

    <div className="small text-muted mt-2">
      Estimates only. Final charges may vary based on carrier audit or remote area surcharges.
    </div>
  </>
)}

{/* …in <Modal.Footer> keep only Close & Get Quotes */}

          <div className="col-md-2">
            <Form.Label>Postcode (opt.)</Form.Label>
            <Form.Control value={postcode} onChange={(e) => setPostcode(e.target.value)} />
          </div>

          <div className="col-md-6">
            <Form.Label>Weight</Form.Label>
            <InputGroup>
              <Form.Control value={weight} onChange={(e) => setWeight(e.target.value)} />
              <Form.Select value={unit} onChange={(e) => setUnit(e.target.value as any)}>
                <option value="kg">kg</option>
                <option value="lb">lb</option>
              </Form.Select>
            </InputGroup>
            <div className="form-text">Chargeable = max(actual, volumetric)</div>
          </div>

          <div className="col-md-6">
            <Form.Label className="d-block">Speed</Form.Label>
            <div className="d-flex gap-2">
              <Button
                size="sm"
                variant={speed === "standard" ? "primary" : "outline-primary"}
                onClick={() => setSpeed("standard")}
              >
                Standard
              </Button>
              <Button
                size="sm"
                variant={speed === "express" ? "primary" : "outline-primary"}
                onClick={() => setSpeed("express")}
              >
                Express
              </Button>
            </div>
          </div>
        </div>

        <Alert variant="light" className="mt-3">
          These are <strong>non-binding estimates</strong>. Final rates are confirmed by our team after
          reviewing exact package details, remote surcharges and carrier availability.
        </Alert>

        {error && <Alert variant="info" className="mt-2">{error}</Alert>}

        {loading && (
          <div className="d-flex justify-content-center py-3">
            <Spinner animation="border" />
          </div>
        )}

        {!loading && quotes.length > 0 && (
          <Table hover responsive className="mt-2">
            <thead>
              <tr>
                <th>Carrier</th>
                <th>Service</th>
                <th>ETA</th>
                <th className="text-end">Chargeable (kg)</th>
                <th className="text-end">Base</th>
                <th className="text-end">Fuel</th>
                <th className="text-end">Remote</th>
                <th className="text-end">Insurance</th>
                <th className="text-end">Total (AED)</th>
                <th style={{ width: 160 }} />
              </tr>
            </thead>
            <tbody>
              {quotes.map((q, i) => (
                <tr key={i}>
                  <td>{q.carrier}</td>
                  <td>{q.speed}</td>
                  <td>{q.etaDays} days</td>
                  <td className="text-end">{q.chargeableKg.toFixed(2)}</td>
                  <td className="text-end">{q.breakdown.baseAED.toFixed(2)}</td>
                  <td className="text-end">{q.breakdown.fuelAED.toFixed(2)}</td>
                  <td className="text-end">{q.breakdown.remoteAED.toFixed(2)}</td>
                  <td className="text-end">{q.breakdown.insuranceAED.toFixed(2)}</td>
                  <td className="text-end fw-bold">{q.priceAED.toFixed(2)}</td>
                  <td className="text-end">
                    <div className="d-flex gap-2 justify-content-end">
                      <Button size="sm" variant="outline-secondary" onClick={() => copyRow(q)}>Copy</Button>
                      <Button size="sm" onClick={() => emailRow(q)}>Email me</Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Modal.Body>
      <Modal.Footer>
        <Button variant="secondary" onClick={onHide}>Close</Button>
        <Button variant="primary" onClick={getQuotes} disabled={loading}>
          {loading ? <Spinner size="sm" /> : "Get Quotes"}
        </Button>
      </Modal.Footer>
    </Modal>
  );
}
